pipeline {
  agent any
  
  stage('Clean Workspace') {
  steps {
    deleteDir()
  }
}
  stages {
    stage('Clone') {
      steps {
        git branch: 'main', url: 'https://github.com/awslab-devops/devops-starter-app.git'
      }
    }

    stage('Build Docker Image') {
  steps {
    sh 'docker build --no-cache -t devops-app .'
  }
}

    stage('Tag Image') {
      steps {
        sh 'docker tag devops-app docker21devops/devops-app:latest'
      }
    }

    stage('Docker Login & Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh '''
          echo "$PASS" | docker login -u "$USER" --password-stdin
          docker push docker21devops/devops-app:latest
          '''
        }
      }
    }

    stage('Deploy Locally') {
      steps {
        sh '''
        docker stop devops-app || true
        docker rm devops-app || true
        docker run -d -p 3000:3000 --restart=always --name devops-app docker21devops/devops-app:latest
        '''
      }
    }
  }
}
