pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/YOUR-USERNAME/devops-starter-app.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devops-app .'
      }
    }

    stage('Tag Image') {
      steps {
        sh 'docker tag devops-app YOUR-DOCKERHUB-USERNAME/devops-app'
      }
    }

    stage('Push to Docker Hub') {
      steps {
        sh 'docker push YOUR-DOCKERHUB-USERNAME/devops-app'
      }
    }
  }
}
