pipeline {
  agent any

  environment {
    IMAGE_NAME = "docker21devops/devops-app"
    IMAGE_TAG = "${BUILD_NUMBER}"   // auto version
    CONTAINER_NAME = "devops-app"
  }
  
  stages {
  stage('Clean Workspace') {
  steps {
    deleteDir()
  }
}
    stage('Clone') {
      steps {
        git branch: 'main', url: 'https://github.com/awslab-devops/devops-starter-app.git'
      }
    }

    stage('Build Docker Image') {
  steps {
    sh 'docker build --no-cache -t devops-app ./devops-starter-app'
  }
}

    stage('Tag Image') {
      steps {
        sh "docker tag devops-app ${IMAGE_NAME}:${IMAGE_TAG}"
        sh "docker tag devops-app ${IMAGE_NAME}:latest"
      }
    }

    stage('Docker Login & Push') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-cred',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
          echo "$PASS" | docker login -u "$USER" --password-stdin
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
          '''
        }
      }
    }

    stage('Deploy') {
  steps {
    sh '''
    docker pull $IMAGE_NAME:$IMAGE_TAG
    docker stop $CONTAINER_NAME || true
    docker rm $CONTAINER_NAME || true
    docker run -d -p 3000:3000 \
      -e BUILD_NUMBER=$IMAGE_TAG \
      --name $CONTAINER_NAME \
      $IMAGE_NAME:$IMAGE_TAG
        '''
      }
    }
  }
}
